[project]
name = "knowledge"
version = "0.0.4"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.0.0",
    "httpx>=0.28.0",
    "python-dotenv>=1.1.0",
    "pydantic>=2.10.0",
    "pydantic-settings>=2.10.0",
    "langchain>=1.0.0",
    "langchain-openai>=1.0.0",
    "langchain-mcp-adapters>=0.1.0",
    "fastapi>=0.115.0",
    "uvicorn[standard]",
    "websockets>=15.0",
    "python-dotenv>=1.2.2",
    "asyncio>=4.0.0",
    "slack-bolt>=1.29.0",
    "slack-sdk>=3.35.0",
    "aiohttp>=3.14.1",
    "kiwipiepy>=0.23.2",
    "chromadb>=1.5.9",
    "opensearch-py>=3.2.0",
    "pypdf>=6.14.2",
    "langchain-community>=0.4.2",
    "sentence-transformers>=5.6.0",
    "langchain-huggingface>=1.2.2",
    "streamlit>=1.59.0",
    "torchvision>=0.27.1",
    "ipykernel>=7.3.0",
    "logging>=0.4.9.6",
]

[dependency-groups]
dev = [
    "python-semantic-release>=10.5.3",
    "pytest>=8.0.0",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.11.0",
]

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]

branch = "main"
tag_format = "v{version}"
commit_parser = "conventional"
allow_zero_version = true
major_on_zero = true

build_command = """
uv lock --upgrade-package "$PACKAGE_NAME"
git add uv.lock
uv build
"""

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"
mode = "update"
mask_initial_release = false

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"

[tool.semantic_release.remote]
name = "origin"
type = "github"

[tool.semantic_release.publish]
dist_glob_patterns = ["dist/*"]
upload_to_vcs_release = true
